version: "3.8"
services:
  chief:
    container_name: chief
    hostname: chief
    image: gcr.io/[GCP-PROJECT]/[CONTAINER]:[TAG]
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS_LOCAL}:/tmp/keys/creds.json:ro
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/keys/creds.json
      TF_CONFIG: "{
        \"cluster\": {
          \"chief\": [\"chief:2222\"],
          \"worker\": [\"worker:2222\"]
        },
        \"task\": {\"type\": \"chief\", \"index\": 0}
      }"
    command: ${COMMAND}
  worker:
    container_name: worker
    hostname: worker
    image: gcr.io/[GCP-PROJECT]/[CONTAINER]:[TAG]
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS_LOCAL}:/tmp/keys/creds.json:ro
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/keys/creds.json
      TF_CONFIG: "{
        \"cluster\": {
          \"chief\": [\"chief:2222\"],
          \"worker\": [\"worker:2222\"]
        },
        \"task\": {\"type\": \"worker\", \"index\": 0}
      }"
    command: ${COMMAND}